### ISSUE TITLE
Document custom XSL support

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#213]
For folks developing pretext-core, it would be helpful to expose the most recent commits from pretext via the cli.  This could be accomplished by having an argument that specifies a core-pretext directory (that the user git-pulls from the pretext project on github).

**Comment by StevenClontz** [comment]
I think https://github.com/PreTeXtBook/pretext-cli/blob/main/scripts/symlink_core.py does much of this. What else do we want to add to it?

**Comment by StevenClontz** [comment]
Oh wait I see; this is so folks would only need to *install* the CLI, not have a copy of an in-development version.

So begrudingly, I think we *do* need to be installing core XSL to `~/.pretext/xsl` in order to solve #180 anyway. So it's not a stretch to add a sibling to `<targets/>` called e.g. `<core-xsl-path/>` to point to a different copy of core XSL.

What we *cannot* do is support swapping out core python. If you want to mess with core Python and the CLI then you need the in-development CLI and need to use symlink_core.py.

**Comment by oscarlevin** [comment]
We now have the ability to use core pretext's xsl via #217.  You can simply specify `<xsl>path/to/pretext/xsl/pretext-html.xsl</xsl>` or the like.  

Do we want to be more explicit about this?  Document it somewhere other than here?  Have a child of `<target>` that says to build against a local core pretext, but still use a separate custom xsl?

**Comment by StevenClontz** [comment]
We should definitely include this as a commented option on our template project.ptx.

**Comment by StevenClontz** [comment]
@oscarlevin put your eyes on 41c3f45 and let me know if it works

**Comment by oscarlevin** [comment]
I added a comment on the commit about one of the comments.  I think this is helpful, although we will want some proper documentation eventually.

**Comment by StevenClontz** [comment]
With your approval of the PR, I hope to soon package up 0.6.2 and submit a PR to core PreTeXt documentation updating the "getting started" section to include deployment to GitHub Pages

**Comment by StevenClontz** [comment]
I definitely don't like `pretext new` building a folder for custom XSL - that seems to send the wrong message. So I think I like removing the commented-out `custom` target from generated project.ptx altogether, and putting this info in documentation only.

**Comment by StevenClontz** [comment]
Removing this from a `pretext new book`

```
    <!-- Custom XSL may invoke core PreTeXt by using pretext-href -->
    <!-- Only files in the directory containing custom.xsl are used -->
    <!-- <target name="custom">
      <format>html</format>
      <source>source/main.ptx</source>
      <publication>publication/publication.ptx</publication>
      <output-dir>output/custom</output-dir>
      <xsl>path/to/your/custom.xsl</xsl>
    </target> -->
```

I think when it comes time to document this, it might make sense to have a new custom-xsl template (`pretext new customxsl`?) to go along with documentation.

**Comment by siefkenj** [comment]
It seems that with the recent changes, using the `xsl` from the `overhaul` branch no longer works with pretext-cli. I get an error that `PROOF-LIKE` is not found. Even though the copied-over `entities.ent` contains the `PROOF-LIKE` environment.

You can reproduce by cloning https://github.com/siefkenj/pretext-react-compiled-article and running the build script.

**Comment by StevenClontz** [comment]
Sorry for the delay, only one week left of classes...

I'm assuming that, for whatever reason, https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/utils.py#L238 is failing to copy the entities.ent file.

Actually, I don't have to assume - here's what I see when I hack in a log after line https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/utils.py#L247

```
$ pretext build -x tmp/pretext/xsl/pretext-html.xsl html-dev
PreTeXt project found in `/home/user/new-pretext-project`.
Building with custom xsl /home/user/new-pretext-project/tmp/pretext/xsl/pretext-html.xsl specified in project.ptx
moving pretext-litprog.xsl to /tmp/tmpgjox553q/pretext-litprog.xsl
moving pretext-smc.xsl to /tmp/tmpgjox553q/pretext-smc.xsl
moving pretext-assembly.xsl to /tmp/tmpgjox553q/pretext-assembly.xsl
moving pretext-text.xsl to /tmp/tmpgjox553q/pretext-text.xsl
moving pretext-html.xsl to /tmp/tmpgjox553q/pretext-html.xsl
moving pretext-sage-doctest.xsl to /tmp/tmpgjox553q/pretext-sage-doctest.xsl
moving support to /tmp/tmpgjox553q/support
moving support/extract-latex-image-labels.xsl to /tmp/tmpgjox553q/support/extract-latex-image-labels.xsl
moving support/README.md to /tmp/tmpgjox553q/support/README.md
moving support/package-math.xsl to /tmp/tmpgjox553q/support/package-math.xsl
moving support/pretext-pg-macros.xsl to /tmp/tmpgjox553q/support/pretext-pg-macros.xsl
moving support/extract-math.xsl to /tmp/tmpgjox553q/support/extract-math.xsl
moving support/runestone-services.xml to /tmp/tmpgjox553q/support/runestone-services.xml
moving support/tactile-svg.xsl to /tmp/tmpgjox553q/support/tactile-svg.xsl
moving extract-latex-image.xsl to /tmp/tmpgjox553q/extract-latex-image.xsl
moving README.md to /tmp/tmpgjox553q/README.md
moving pretext-runestone-static.xsl to /tmp/tmpgjox553q/pretext-runestone-static.xsl
moving extract-youtube.xsl to /tmp/tmpgjox553q/extract-youtube.xsl
moving publisher-variables.xsl to /tmp/tmpgjox553q/publisher-variables.xsl
moving localizations to /tmp/tmpgjox553q/localizations
moving localizations/fi-FI.xml to /tmp/tmpgjox553q/localizations/fi-FI.xml
moving localizations/ca-ES.xml to /tmp/tmpgjox553q/localizations/ca-ES.xml
moving localizations/pt-BR.xml to /tmp/tmpgjox553q/localizations/pt-BR.xml
moving localizations/de-DE.xml to /tmp/tmpgjox553q/localizations/de-DE.xml
moving localizations/README.md to /tmp/tmpgjox553q/localizations/README.md
moving localizations/cs-CZ.xml to /tmp/tmpgjox553q/localizations/cs-CZ.xml
moving localizations/hu-HU.xml to /tmp/tmpgjox553q/localizations/hu-HU.xml
moving localizations/es-ES.xml to /tmp/tmpgjox553q/localizations/es-ES.xml
moving localizations/pt-PT.xml to /tmp/tmpgjox553q/localizations/pt-PT.xml
moving localizations/en-US.xml to /tmp/tmpgjox553q/localizations/en-US.xml
moving localizations/af-ZA.xml to /tmp/tmpgjox553q/localizations/af-ZA.xml
moving localizations/bg-BG.xml to /tmp/tmpgjox553q/localizations/bg-BG.xml
moving localizations/fr-CA.xml to /tmp/tmpgjox553q/localizations/fr-CA.xml
moving localizations/localizations.xml to /tmp/tmpgjox553q/localizations/localizations.xml
moving localizations/fr-FR.xml to /tmp/tmpgjox553q/localizations/fr-FR.xml
moving localizations/it-IT.xml to /tmp/tmpgjox553q/localizations/it-IT.xml
moving pretext-numbers.xsl to /tmp/tmpgjox553q/pretext-numbers.xsl
moving extract-sageplot.xsl to /tmp/tmpgjox553q/extract-sageplot.xsl
moving pretext-beamer.xsl to /tmp/tmpgjox553q/pretext-beamer.xsl
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/pretext-cli-1KkGAqOF/bin/pretext", line 33, in <module>
    sys.exit(load_entry_point('pretextbook', 'console_scripts', 'pretext')())
  File "/home/user/.local/share/virtualenvs/pretext-cli-1KkGAqOF/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/pretext-cli-1KkGAqOF/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/pretext-cli-1KkGAqOF/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/pretext-cli-1KkGAqOF/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/pretext-cli-1KkGAqOF/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/pretext-cli/pretext/cli.py", line 239, in build
    project.build(target_name,webwork,diagrams,diagrams_format,only_assets,clean)
  File "/home/user/pretext-cli/pretext/project.py", line 246, in build
    utils.copy_fix_xsl(target.xsl_path(), temp_xsl_dir)
  File "/home/user/pretext-cli/pretext/utils.py", line 257, in copy_fix_xsl
    lxml_element = ET.parse(filename)
  File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "pretext-beamer.xsl", line 655
lxml.etree.XMLSyntaxError: Entity 'PROOF-LIKE' not defined, line 655, column 34
```

```
$ ls tmp/pretext/xsl/
README.md                          extract-pg.xsl                     pretext-beamer.xsl                 pretext-latex.xsl                  pretext-sage-doctest.xsl           pretext-ww-problem-sets.xsl
entities.ent                       extract-sageplot.xsl               pretext-braille.xsl                pretext-litprog.xsl                pretext-smc.xsl                    publisher-variables.xsl
extract-asymptote.xsl              extract-youtube.xsl                pretext-common.xsl                 pretext-merge.xsl                  pretext-solution-manual-latex.xsl  support/
extract-identity.xsl               latex/                             pretext-epub.xsl                   pretext-numbers.xsl                pretext-text-utilities.xsl         utilities/
extract-interactive.xsl            localizations/                     pretext-html.xsl                   pretext-revealjs.xsl               pretext-text.xsl                   
extract-latex-image.xsl            pretext-assembly.xsl               pretext-json-manifest.xsl          pretext-runestone-static.xsl       pretext-units.xsl                  
extract-mom.xsl                    pretext-basic-html.xsl             pretext-jupyter.xsl                pretext-runestone.xsl              pretext-view-source.xsl   
```

```
$ ls /tmp/tmpgjox553q
README.md                extract-sageplot.xsl  localizations         pretext-html.xsl     pretext-numbers.xsl           pretext-sage-doctest.xsl  pretext-text.xsl         support
extract-latex-image.xsl  extract-youtube.xsl   pretext-assembly.xsl  pretext-litprog.xsl  pretext-runestone-static.xsl  pretext-smc.xsl           publisher-variables.xsl
```

**Comment by siefkenj** [comment]
Very strange. I thought I saw `entities.ent` in my tmp folder when I looked.

**Comment by StevenClontz** [comment]
Not half as strange as I have no idea why `for filename in glob.iglob('**', recursive=True):` is only grabbing a random (but consistent) subset of files...

**Comment by arechnitzer** [comment]
What is the status of this? I am encountering similar errors with my styling hackery "Entity GOAL-LIKE" not defined - etc etc.

**Comment by StevenClontz** [comment]
Status is it's finals week and I have a PreTeXt-related grant submission due on the 9th. :-( @oscarlevin might have better luck attacking this than I have for a couple weeks.
