### ISSUE TITLE
fix generate interactive

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#265]
```
Traceback (most recent call last):
  File "/home/user/.local/bin/pretext", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pretext/cli.py", line 296, in build
    project.generate(target_name)
  File "/home/user/.local/lib/python3.8/site-packages/pretext/project.py", line 295, in generate
    generate.interactive(
  File "/home/user/.local/lib/python3.8/site-packages/pretext/generate.py", line 123, in interactive
    utils.check_asset_execs('interactive', formats[target_format])
NameError: name 'formats' is not defined
```

https://groups.google.com/d/msgid/pretext-dev/36b57d60-398d-4f81-9014-c71589f95519n%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by StevenClontz** [comment]
closed by 70976cac65d8b3c934b3b62e508c832beaca29d3
