### ISSUE TITLE
`ptx_version` required even for legacy projects?

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#502]
I might have relented too soon, @bjones1.  

Steps to reproduce:
- on the `refactor2` branch, after merged pull request.
- `pretext new && cd new-pretext-project`
- `pretext support`

Here is the output:
```
PreTeXt project found in `/workspaces/pretext-cli/new-pretext-project`.

Please share the following information when posting to the
pretext-support Google Group.

PreTeXt-CLI version: 1.7.3
    PyPI link: https://pypi.org/project/pretextbook/1.7.3/
PreTeXt core resources commit: 9bce7e55911fb14e3e6e362bfa78bd6431c38597
Runestone Services version: 6.5.0
OS: Linux-5.15.0-1042-azure-x86_64-with-glibc2.31
Python version: 3.11.4
Current working directory: /workspaces/pretext-cli/new-pretext-project
PreTeXt project path: /workspaces/pretext-cli/new-pretext-project

Contents of project.ptx:
------------------------
<!--
    This file provides the overall configuration for your PreTeXt
    project. To edit the content of your document, open `source/main.ptx`
    (default location).
--><project>
  <targets>
    <!-- To build this target, run `pretext build web` -->
    <target name="web">
      <format>html</format>
      <source>source/main.ptx</source>
      <publication>publication/publication.ptx</publication>
      <output-dir>output/web</output-dir>
    </target>
    <target name="print" pdf-method="xelatex">
      <format>pdf</format>
      <source>source/main.ptx</source>
      <publication>publication/publication.ptx</publication>
      <output-dir>output/print</output-dir>
    </target>
    <target name="print-latex">
      <format>latex</format>
      <source>source/main.ptx</source>
      <publication>publication/publication.ptx</publication>
      <output-dir>output/print-latex</output-dir>
    </target>
    <target name="subset">
      <!-- Usage: to build starting at XMLID, -->
      <!-- pretext build subset -x XMLID      -->
      <!-- or use <xml-root>XMLID</xml-root>  -->
      <format>html</format>
      <source>source/main.ptx</source>
      <publication>publication/publication.ptx</publication>
      <output-dir>output/subset</output-dir>
      <stringparam key="debug.skip-knowls" value="yes"/>
    </target>
  </targets>
  <executables>
    <latex>latex</latex>
    <pdflatex>pdflatex</pdflatex>
    <xelatex>xelatex</xelatex>
    <pdfsvg>pdf2svg</pdfsvg>
    <asy>asy</asy>
    <sage>sage</sage>
    <pdfpng>convert</pdfpng>
    <pdfeps>pdftops</pdfeps>
    <node>node</node>
    <liblouis>file2brl</liblouis>
  </executables>
</project>
------------------------
Traceback (most recent call last):
  File "/usr/local/bin/pretext", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/pretext-cli/pretext/cli.py", line 145, in support
    project = Project()
              ^^^^^^^^^
  File "/workspaces/pretext-cli/pretext/project/__init__.py", line 541, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Project
ptx_version
  field required (type=value_error.missing)
```

But changing line 513 to 1    `ptx_version: t.Optional[str] = pxml.attr(name="ptx-version")` and running `pretext support` completes without error.

**Comment by bjones1** [comment]
Thanks for reporting, I just pushed a fix. `Project()` is now `Project.parse()`.

**Comment by bjones1** [comment]
Let me know if there's any other problems here!
