### ISSUE TITLE
nicer errors for invalid v2 project.ptx

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#547]
project.ptx:

```
<project ptx-version="2">
  <targets>
    <target name="web" format="html"/>
    <target name="print" format="pdf"/>
    <target format="latex"/>
  </targets>
</project>
```

error output:

```
PreTeXt project found in `/workspaces/super-duper-lamp/new-pretext-project`.
Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/pretext", line 8, in <module>
    sys.exit(main())
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pretext/cli.py", line 372, in build
    project = Project.parse()
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pretext/project/__init__.py", line 924, in parse
    p = Project.from_xml(xml_bytes)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/model.py", line 302, in from_xml
    return cls.from_xml_tree(etree.fromstring(source))
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/model.py", line 286, in from_xml_tree
    obj = typing.cast(ModelT, cls.__xml_serializer__.deserialize(XmlElement.from_native(root)))
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 76, in deserialize
    result = {
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 79, in <dictcomp>
    if (field_value := field_serializer.deserialize(element)) is not None
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/wrapper.py", line 75, in deserialize
    return self._inner_serializer.deserialize(sub_element)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/homogeneous.py", line 75, in deserialize
    while (value := self._inner_serializer.deserialize(element)) is not None:
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 156, in deserialize
    return super().deserialize(sub_element)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 116, in deserialize
    return self._model.__xml_serializer__.deserialize(element)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 86, in deserialize
    return self._model.parse_obj(obj)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pretext/project/__init__.py", line 222, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 877, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 306, in pydantic.class_validators._generic_validator_cls.lambda5
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pretext/project/__init__.py", line 167, in output_dir_validator
    return Path(v) if v is not None else Path(values["name"])
KeyError: 'name'
```

desired error:

```
One of your `<target/>`s is missing a `name`. Try setting `name="my-target-name"` for each target.
```

**Comment by StevenClontz** [comment]
project.ptx:

```xml
<project ptx-version="2">
  <targets>
    <target name="web" format="html"/>
    <target name="print" format="pdf"/>
    <target name="print-latex"/>
  </targets>
</project>

```

Error:

```
PreTeXt project found in `/workspaces/super-duper-lamp/new-pretext-project`.
Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/pretext", line 8, in <module>
    sys.exit(main())
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pretext/cli.py", line 372, in build
    project = Project.parse()
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pretext/project/__init__.py", line 924, in parse
    p = Project.from_xml(xml_bytes)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/model.py", line 302, in from_xml
    return cls.from_xml_tree(etree.fromstring(source))
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/model.py", line 286, in from_xml_tree
    obj = typing.cast(ModelT, cls.__xml_serializer__.deserialize(XmlElement.from_native(root)))
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 76, in deserialize
    result = {
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 79, in <dictcomp>
    if (field_value := field_serializer.deserialize(element)) is not None
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/wrapper.py", line 75, in deserialize
    return self._inner_serializer.deserialize(sub_element)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/homogeneous.py", line 75, in deserialize
    while (value := self._inner_serializer.deserialize(element)) is not None:
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 156, in deserialize
    return super().deserialize(sub_element)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 116, in deserialize
    return self._model.__xml_serializer__.deserialize(element)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pydantic_xml/serializers/factories/model.py", line 86, in deserialize
    return self._model.parse_obj(obj)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pretext/project/__init__.py", line 222, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 877, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 306, in pydantic.class_validators._generic_validator_cls.lambda5
  File "/opt/python/3.10.8/lib/python3.10/site-packages/pretext/project/__init__.py", line 127, in platform_validator
    if values["format"] == Format.HTML:
KeyError: 'format'
```

Desired error:

```
Your `<target/>` named `print-latex` is missing a format. Try setting `format="html"` or another format.
```

**Comment by oscarlevin** [comment]
@bjones1, could you explain how we are ensuring that `name` and `format` are required?  This error is being thrown when a validator is trying find `values["name"]` as a keyError.  But isn't the idea that if "target.name" isn't specified, we should get an error right away?

**Comment by bjones1** [comment]
Oops, I didn't think of that case. The `platform_validator` gets run before the main validator which will error if name/format aren't defined. We should use `values.get("format")` or `values.get("name")` in the validators instead. Does that make sense?

**Comment by oscarlevin** [comment]
Perfect.  I'll do that now.
