### ISSUE TITLE
character map issue?

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#69]
I get the following failure when running `pretext build latex` against the book here: https://github.com/oscarlevin/math795-fall20.

Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\pretext.exe\__main__.py", line 7, in <module>
  File "C:\Users\oscar.levin\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\oscar.levin\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\oscar.levin\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\oscar.levin\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\oscar.levin\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\pretext\cli.py", line 148, in build
    build.latex(source,latex_output,stringparams)
  File "c:\python38\lib\site-packages\pretext\build.py", line 49, in latex
    xsltproc(xslfile, ptxfile, outfile='main.tex', outdir=output, stringparams=stringparams)
  File "c:\python38\lib\site-packages\pretext\build.py", line 124, in xsltproc
    fh.write(str(newdom))
  File "c:\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2061' in position 81711: character maps to <undefined>

No issues with `pretext build html`.  Any ideas?

**Comment by rbeezer** [comment]
There is some weirdness with `lxml` and `xsltproc` and `xsl:output` to get UTF-8 output.  Not clear if that is in play here.  I think I sort of dodged the issue in `pretext/pretext.py` (easy to find if you search on `UTF-8`).

Maybe try
```python
fh.write(str(newdom).encode('utf-8'))
```
just to see if it makes the error go away?

**Comment by oscarlevin** [comment]
Almost.  What did work (I think) was to use

`with open(outfile, "w", encoding='utf-8') as fh:
                fh.write(str(newdom))`

Change at c48c9f1

@StevenClontz, can we publish this as a bugfix?  I forget our process for such things.

**Comment by StevenClontz** [comment]
Sure we can push this as 1.1.2, although if you've already made the change
in 2.0rc0 I'll have to look up some Git mechanics. This task is in my queue.


Steven Clontz
https://clontz.org - steven.clontz@gmail.com

**Comment by StevenClontz** [comment]
Eh, I pushed a single-commit hotfix and published to PyPI, but someone should probably confirm that I didn't screw it up before we close this.
